/**
 * Pamphlet theme catalogue.
 *
 * Each theme maps to a beautiful static background illustration
 * (Hanuman + ornate Indian devotional decoration) sitting in
 * /public/pamphlet-bg/<id>-thumb.jpg. The four backgrounds were AI-
 * generated ONCE in Adobe Firefly using the existing Lucknow
 * pamphlet corpus as style references, then committed as static
 * assets, so per-pamphlet runtime cost is ZERO.
 *
 * The Satori composer (`composeAiPamphlet` in
 * src/app/api/pamphlet/route.tsx) layers the chosen background as a
 * full-bleed bottom layer, then overlays the personalised Devanagari
 * invitation copy (generated by free Gemini text) on top of the
 * empty parchment zone the illustration intentionally leaves on the
 * right.
 *
 * Adding a new theme:
 *   1. Drop the background PNG/WebP into /public/pamphlet-bg/<id>-thumb.jpg
 *      with Hanuman on the LEFT half and the right half kept clean
 *      for text overlay
 *   2. Add the id to PamphletArtTheme union
 *   3. Add the catalogue entry to PAMPHLET_THEMES below
 */
export type PamphletArtTheme =
  | "panchmukhi-mandir"
  | "royal-awadhi"
  | "festive-marigold"
  | "minimal-modern";

export const PAMPHLET_THEMES: {
  id: PamphletArtTheme;
  label: { en: string; hi: string };
  tagline: { en: string; hi: string };
  /** Path under /public for the thumbnail shown in the picker UI.
   *  Same file as the background, Satori uses the full-res one,
   *  the picker uses CSS to render it small. */
  thumb: string;
}[] = [
  {
    id: "panchmukhi-mandir",
    label: { en: "Panchmukhi Mandir", hi: "पंचमुखी मंदिर" },
    tagline: {
      en: "Five-faced Hanuman, prasad bowls, vine border",
      hi: "पंचमुखी हनुमान, प्रसाद थाली, फूलों की बेल",
    },
    thumb: "/pamphlet-bg/panchmukhi-mandir-thumb.jpg",
  },
  {
    id: "royal-awadhi",
    label: { en: "Royal Awadhi", hi: "अवधी राजसी" },
    tagline: {
      en: "Standing Hanuman, temple arch, peacocks",
      hi: "खड़े हनुमान, मंदिर मेहराब, मोर",
    },
    thumb: "/pamphlet-bg/royal-awadhi-thumb.jpg",
  },
  {
    id: "festive-marigold",
    label: { en: "Festive Marigold", hi: "उत्सवी गेंदा" },
    tagline: {
      en: "Sundarkand, marigold cascades, brass diyas",
      hi: "सुंदरकांड, गेंदा माला, पीतल के दीये",
    },
    thumb: "/pamphlet-bg/festive-marigold-thumb.jpg",
  },
  {
    id: "minimal-modern",
    label: { en: "Minimal Modern", hi: "आधुनिक" },
    tagline: {
      en: "Meditating Hanuman, mandala, clean lines",
      hi: "ध्यानमग्न हनुमान, मंडल, साफ रेखाएँ",
    },
    thumb: "/pamphlet-bg/minimal-modern-thumb.jpg",
  },
];
